# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(392, 172)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(10, 10, 371, 151))
        self.frame.setStyleSheet("background-color:#03adfc;\n"
"border: solid #03fca1;\n"
"border-radius:7px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.change_frame = QtWidgets.QFrame(self.frame)
        self.change_frame.setGeometry(QtCore.QRect(280, 40, 71, 91))
        self.change_frame.setStyleSheet("background:#9003fc;\n"
"border-radius:7px;")
        self.change_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.change_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.change_frame.setObjectName("change_frame")
        self.change = QtWidgets.QPushButton(self.change_frame)
        self.change.setGeometry(QtCore.QRect(5, 15, 61, 23))
        self.change.setStyleSheet("background:#fcba03;")
        self.change.setObjectName("change")
        self.change_2 = QtWidgets.QPushButton(self.change_frame)
        self.change_2.setGeometry(QtCore.QRect(5, 58, 61, 21))
        self.change_2.setStyleSheet("background:#fcba03;")
        self.change_2.setObjectName("change_2")
        self.ed_frame = QtWidgets.QFrame(self.frame)
        self.ed_frame.setEnabled(True)
        self.ed_frame.setGeometry(QtCore.QRect(10, 39, 261, 91))
        self.ed_frame.setStyleSheet("background:#fcba03;\n"
"border-radius:7px;\n"
"\n"
"")
        self.ed_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ed_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ed_frame.setObjectName("ed_frame")
        self.ed = QtWidgets.QLineEdit(self.ed_frame)
        self.ed.setGeometry(QtCore.QRect(10, 20, 241, 16))
        self.ed.setStyleSheet("background:#e6ebf2;")
        self.ed.setObjectName("ed")
        self.ed_2 = QtWidgets.QLineEdit(self.ed_frame)
        self.ed_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.ed_2.setStyleSheet("background:#e6ebf2;")
        self.ed_2.setObjectName("ed_2")
        self.lab = QtWidgets.QLabel(self.ed_frame)
        self.lab.setGeometry(QtCore.QRect(10, 20, 241, 16))
        self.lab.setStyleSheet("background:#9003fc;")
        self.lab.setText("")
        self.lab.setObjectName("lab")
        self.lab_2 = QtWidgets.QLabel(self.ed_frame)
        self.lab_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.lab_2.setStyleSheet("background:#9003fc;")
        self.lab_2.setText("")
        self.lab_2.setObjectName("lab_2")
        self.label = QtWidgets.QLabel(self.ed_frame)
        self.label.setGeometry(QtCore.QRect(30, 0, 91, 16))
        self.label.setStyleSheet("font-size:9pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.ed_frame)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.label_2.setStyleSheet("font-size:9pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.label_2.setObjectName("label_2")
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(293, 6, 75, 23))
        self.close.setStyleSheet("background:#9003fc;\n"
"border-radius:7px;")
        self.close.setObjectName("close")
        self.text = QtWidgets.QLabel(self.frame)
        self.text.setGeometry(QtCore.QRect(30, 10, 221, 20))
        self.text.setStyleSheet("font-size:13pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.text.setObjectName("text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.change.setText(_translate("Form", "изменить"))
        self.change_2.setText(_translate("Form", "изменить"))
        self.label.setText(_translate("Form", "Токен сюда:"))
        self.label_2.setText(_translate("Form", "id сюда:"))
        self.close.setText(_translate("Form", "X"))
        self.text.setText(_translate("Form", "Добавление данных"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
