# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(562, 475)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 10, 561, 461))
        self.frame.setStyleSheet("background-color:#03adfc;\n"
"border: solid #03fca1;\n"
"border-radius:7px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.change_frame = QtWidgets.QFrame(self.frame)
        self.change_frame.setGeometry(QtCore.QRect(470, 40, 71, 91))
        self.change_frame.setStyleSheet("background:#9003fc;\n"
"border-radius:7px;")
        self.change_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.change_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.change_frame.setObjectName("change_frame")
        self.change = QtWidgets.QPushButton(self.change_frame)
        self.change.setGeometry(QtCore.QRect(5, 15, 61, 23))
        self.change.setStyleSheet("background:#fcba03;")
        self.change.setObjectName("change")
        self.change_2 = QtWidgets.QPushButton(self.change_frame)
        self.change_2.setGeometry(QtCore.QRect(5, 58, 61, 21))
        self.change_2.setStyleSheet("background:#fcba03;")
        self.change_2.setObjectName("change_2")
        self.ed_frame = QtWidgets.QFrame(self.frame)
        self.ed_frame.setEnabled(True)
        self.ed_frame.setGeometry(QtCore.QRect(200, 39, 261, 91))
        self.ed_frame.setStyleSheet("background:#fcba03;\n"
"border-radius:7px;\n"
"\n"
"")
        self.ed_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ed_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ed_frame.setObjectName("ed_frame")
        self.ed = QtWidgets.QLineEdit(self.ed_frame)
        self.ed.setGeometry(QtCore.QRect(10, 20, 241, 16))
        self.ed.setStyleSheet("background:#e6ebf2;")
        self.ed.setObjectName("ed")
        self.ed_2 = QtWidgets.QLineEdit(self.ed_frame)
        self.ed_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.ed_2.setStyleSheet("background:#e6ebf2;")
        self.ed_2.setObjectName("ed_2")
        self.lab = QtWidgets.QLabel(self.ed_frame)
        self.lab.setGeometry(QtCore.QRect(10, 20, 241, 16))
        self.lab.setStyleSheet("background:#9003fc;")
        self.lab.setText("")
        self.lab.setObjectName("lab")
        self.lab_2 = QtWidgets.QLabel(self.ed_frame)
        self.lab_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.lab_2.setStyleSheet("background:#9003fc;")
        self.lab_2.setText("")
        self.lab_2.setObjectName("lab_2")
        self.label = QtWidgets.QLabel(self.ed_frame)
        self.label.setGeometry(QtCore.QRect(30, 0, 91, 16))
        self.label.setStyleSheet("font-size:9pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.ed_frame)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.label_2.setStyleSheet("font-size:9pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.label_2.setObjectName("label_2")
        self.close = QtWidgets.QPushButton(self.frame)
        self.close.setGeometry(QtCore.QRect(470, 5, 75, 23))
        self.close.setStyleSheet("background:#9003fc;\n"
"border-radius:7px;")
        self.close.setObjectName("close")
        self.text = QtWidgets.QLabel(self.frame)
        self.text.setGeometry(QtCore.QRect(230, 10, 221, 20))
        self.text.setStyleSheet("font-size:13pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.text.setObjectName("text")
        self.start = QtWidgets.QPushButton(self.frame)
        self.start.setGeometry(QtCore.QRect(50, 80, 75, 23))
        self.start.setStyleSheet("background:#fcba03;")
        self.start.setObjectName("start")
        self.off = QtWidgets.QPushButton(self.frame)
        self.off.setGeometry(QtCore.QRect(50, 80, 75, 23))
        self.off.setStyleSheet("background:#fcba03;")
        self.off.setObjectName("off")
        self.text_2 = QtWidgets.QLabel(self.frame)
        self.text_2.setGeometry(QtCore.QRect(70, 30, 41, 20))
        self.text_2.setStyleSheet("font-size:13pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.text_2.setObjectName("text_2")
        self.text_3 = QtWidgets.QLabel(self.frame)
        self.text_3.setGeometry(QtCore.QRect(230, 190, 221, 20))
        self.text_3.setStyleSheet("font-size:13pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.text_3.setObjectName("text_3")
        self.text_4 = QtWidgets.QLabel(self.frame)
        self.text_4.setGeometry(QtCore.QRect(30, 190, 121, 20))
        self.text_4.setStyleSheet("font-size:13pt;\n"
"\n"
"font-weight:bold;\n"
"font-style:italic;")
        self.text_4.setObjectName("text_4")
        self.save = QtWidgets.QPushButton(self.frame)
        self.save.setGeometry(QtCore.QRect(200, 150, 151, 21))
        self.save.setStyleSheet("background:#fcba03;\n"
"font-size:11pt;")
        self.save.setObjectName("save")
        self.list_item_0 = QtWidgets.QFrame(self.frame)
        self.list_item_0.setGeometry(QtCore.QRect(0, 220, 540, 40))
        self.list_item_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_item_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_item_0.setObjectName("list_item_0")
        self.com_0 = QtWidgets.QLineEdit(self.list_item_0)
        self.com_0.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.com_0.setStyleSheet("background:white;")
        self.com_0.setObjectName("com_0")
        self.link_0 = QtWidgets.QPushButton(self.list_item_0)
        self.link_0.setGeometry(QtCore.QRect(460, 10, 75, 23))
        self.link_0.setStyleSheet("background:#fcba03;")
        self.link_0.setObjectName("link_0")
        self.link_ed_0 = QtWidgets.QLineEdit(self.list_item_0)
        self.link_ed_0.setGeometry(QtCore.QRect(160, 10, 271, 20))
        self.link_ed_0.setStyleSheet("background:white;")
        self.link_ed_0.setObjectName("link_ed_0")
        self.mask_0 = QtWidgets.QLabel(self.list_item_0)
        self.mask_0.setGeometry(QtCore.QRect(150, 10, 291, 20))
        self.mask_0.setStyleSheet("background-color: transparent;")
        self.mask_0.setText("")
        self.mask_0.setObjectName("mask_0")
        self.list_widget = QtWidgets.QListWidget(self.frame)
        self.list_widget.setGeometry(QtCore.QRect(80, 320, 401, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.list_widget.setFont(font)
        self.list_widget.setAutoFillBackground(False)
        self.list_widget.setStyleSheet("background:#fcba03;")
        self.list_widget.setObjectName("list_widget")
        self.add_item = QtWidgets.QPushButton(self.frame)
        self.add_item.setGeometry(QtCore.QRect(220, 280, 121, 23))
        self.add_item.setStyleSheet("background:#fcba03;")
        self.add_item.setObjectName("add_item")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.change.setText(_translate("Form", "изменить"))
        self.change_2.setText(_translate("Form", "изменить"))
        self.label.setText(_translate("Form", "Токен сюда:"))
        self.label_2.setText(_translate("Form", "id сюда:"))
        self.close.setText(_translate("Form", "X"))
        self.text.setText(_translate("Form", "Добавление данных"))
        self.start.setText(_translate("Form", "Запустить"))
        self.off.setText(_translate("Form", "Выключить"))
        self.text_2.setText(_translate("Form", "Бот"))
        self.text_3.setText(_translate("Form", "Приложения:"))
        self.text_4.setText(_translate("Form", "Комманды:"))
        self.save.setText(_translate("Form", "Сохранить"))
        self.link_0.setText(_translate("Form", "Выбрать"))
        self.list_widget.setToolTip(_translate("Form", "<html><head/><body><p>3ret</p></body></html>"))
        self.add_item.setText(_translate("Form", "добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
